### ISSUE TITLE
22.py convert to float

### ISSUE THREAD

**Issue by CharlesFr** [tomgs/sentdexworkarounds#3]
You need to convert the values to floats before doing arithmetic in the append. Took me ages to work out what wasn't working.

**Comment by TomGranot** [comment]
Not following - didn't I do that?

		            if "B" in value:
		                value = float(value.replace("B",'')) * 1000000000

		            elif "M" in value:
		                value = float(value.replace("M",'')) * 1000000

		            elif "K" in value:
		                value = float(value.replace("K",'')) * 1000

**Comment by CharlesFr** [comment]
I should have been clearer, in the DataFrame append:

`'Trailing P/E':value_list[35] / value_list[19]`

should be:

`'Trailing P/E': str( float(value_list[35]) / float(value_list[19]) )`

ps: would you mind also sharing "key_stats_acc_perf_WITH_NA_enhanced.csv"?

**Comment by TomGranot** [comment]
This was a while back, I wonder now how it worked in the first place. 
Thanks for the fix - added it.

Unfortunately I don't have the file anymore - switched computers since then and didn't save the tutorial folder.
